### ISSUE TITLE
Shading for Docker Java causes an issue with no being able to resolve JNA classes

### ISSUE THREAD

**Issue by m-raab** [bmuschko/gradle-docker-plugin#1147]
I created a plugin to build Docker images based on your plugin. I call DockerBuildImage, but after the update to version 9.1.0 I get an exception:
```
Exception in thread "docker-java-stream--358492054" java.lang.UnsatisfiedLinkError: 'java.lang.String com.bmuschko.gradle.docker.shaded.com.sun.jna.Native.getNativeVersion()'
	at com.bmuschko.gradle.docker.shaded.com.sun.jna.Native.getNativeVersion(Native Method)
	at com.bmuschko.gradle.docker.shaded.com.sun.jna.Native.<clinit>(Native.java:223)
	at com.bmuschko.gradle.docker.shaded.com.github.dockerjava.transport.DomainSocket.<clinit>(DomainSocket.java:54)
	at com.bmuschko.gradle.docker.shaded.com.github.dockerjava.transport.UnixSocket.get(UnixSocket.java:29)
	at com.bmuschko.gradle.docker.shaded.com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl$2.createSocket(ApacheDockerHttpClientImpl.java:153)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:125)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:409)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:164)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:174)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:135)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:172)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:93)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:128)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:116)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:178)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:67)
	at com.bmuschko.gradle.docker.shaded.com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:191)
	at com.bmuschko.gradle.docker.shaded.com.github.dockerjava.httpclient5.ApacheDockerHttpClient.execute(ApacheDockerHttpClient.java:9)
	at com.bmuschko.gradle.docker.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
	at com.bmuschko.gradle.docker.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

It is working with version 9.0.1. I use Docker Desktop on MacOS.

The task 

### Expected Behavior
DockerBuildImage should run like before.

### Current Behavior
The task DockerBuildImage was working in version 9.0.1, but after the update to 9.1.0 with the same configuration it does not work. Please see the exception above.

### Context
Gradle 7.6

### Steps to Reproduce (for bugs)
See project https://github.com/m-raab/docker_gradle_testproject
and run ```gradlew :buildMyAppImage```

### Your Environment
I use Docker Desktop on MacOS - Docker Desktop 4.15.0 (93002) 
JDK 11 is used.

**Comment by bmuschko** [comment]
I can't seem to reproduce the issue you reported with your GitHub repository. The failure I see is the following, but only because you probably don't provide a value for the `BASE_IMAGE` arg.

```
* What went wrong:
Execution failed for task ':buildMyAppImage'.
> Could not build image: base name ($BASE_IMAGE) should not be blank
```

**Comment by m-raab** [comment]
Sorry, but the Gradle task fails before. On my test project the exception is different, but the result is the same ...

```
Exception in thread "docker-java-stream--354181745" java.lang.NoClassDefFoundError: Could not initialize class com.bmuschko.gradle.docker.shaded.com.github.dockerjava.transport.DomainSocket
        at com.bmuschko.gradle.docker.shaded.com.github.dockerjava.transport.UnixSocket.get(UnixSocket.java:29)
        at com.bmuschko.gradle.docker.shaded.com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl$2.createSocket(ApacheDockerHttpClientImpl.java:153)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:125)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:409)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:164)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:174)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:135)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:172)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:93)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:128)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:116)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:178)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:67)
        at com.bmuschko.gradle.docker.shaded.com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:191)
        at com.bmuschko.gradle.docker.shaded.com.github.dockerjava.httpclient5.ApacheDockerHttpClient.execute(ApacheDockerHttpClient.java:9)
        at com.bmuschko.gradle.docker.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
        at com.bmuschko.gradle.docker.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
        at java.base/java.lang.Thread.run(Thread.java:829)
<-------------> 0% EXECUTING [39s]
> :buildMyAppImage

```

On the end the gradle execution hangs. Is this a problem with DockerDesktop on Mac or a problem of the JDK?

```
 ~/ docker -v
Docker version 20.10.21, build baeda1f
 ~/ java -version
openjdk version "11.0.16.1" 2022-08-12
OpenJDK Runtime Environment Temurin-11.0.16.1+1 (build 11.0.16.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.16.1+1 (build 11.0.16.1+1, mixed mode)
```

**Comment by big-andy-coates** [comment]
I'm seeing the same issue on my M1 MacBook Pro.

**Comment by big-andy-coates** [comment]
I thought I'd try cloning the repo locally and running the tests to see what fails, but it looks like the tests aren't set up to work on Mac, so the failures I'm getting don't look to be related to this issue.

**Comment by bmuschko** [comment]
@big-andy-coates What repository are you referring to? I can usually run the tests with Docker Desktop on MacOSX if you are referring to https://github.com/bmuschko/gradle-docker-plugin.

**Comment by bmuschko** [comment]
@m-raab Can you please provide the info on the version of MacOS and whether you are on M1?

**Comment by big-andy-coates** [comment]
> @big-andy-coates What repository are you referring to? I can usually run the tests with Docker Desktop on MacOSX if you are referring to https://github.com/bmuschko/gradle-docker-plugin, however, I don't have a M1.

Interesting! Yes, I'm referring to this repo, cloned to my M1 Mac.

One of the failing tests is a simple ordering issue. (I can create a PR for that). Then it got a lot harder to determine the failure cause.

I can dig a little deeper and maybe share some more info. The failures may be related to this issue.

Unfortunately, it looks like there is still no GutHub winter for M1: https://github.com/actions/runner-images/issues/2187

**Comment by m-raab** [comment]
I'm using a Mac with Intel processor. But I want use "unix:///var/run/docker.sock" instead of "tcp://0.0.0.0:2375" for the connection to the daemon. So I changed my configuration for an additional test.

1. I run ```socat -d TCP-LISTEN:2375,range=127.0.0.1/32,reuseaddr,fork UNIX:/var/run/docker.sock```. The port is not exposed on Mac. See https://github.com/docker/for-mac/issues/770 
2. I added the configuration in the build script 
```
docker {
    url.set("tcp://localhost:2375")
}
```

This is working! So it seems, that the default connection over /var/run/docker.sock is not working in 9.1.0.

```
 ~/ ls -la /var/run/docker.sock
lrwxr-xr-x@ 1 root  daemon  36  6 Jan 10:50 /var/run/docker.sock -> /Users/mraab/.docker/run/docker.sock
 ~/ ls -la /Users/mraab/.docker/run/docker.sock
srwxr-xr-x@ 1 mraab  staff  0  6 Jan 10:50 /Users/mraab/.docker/run/docker.sock
```

I think that the reason for ```Could not initialize class com.bmuschko.gradle.docker.shaded.com.github.dockerjava.transport.DomainSocket```. But why is this working in version 9.0.1?

**Comment by Sineaggi** [comment]
It's possible that jna doesn't support relocation https://github.com/bmuschko/gradle-docker-plugin/pull/1144/files

**Comment by Sineaggi** [comment]
FYI as mentioned in https://github.com/bmuschko/gradle-docker-plugin/issues/1070#issuecomment-1136064227 if you run Gradle with java 16+, it'll use the new `java.net.UnixDomainSocketAddress` and avoid the jna issues.

**Comment by Sineaggi** [comment]
We could exclude jna from being shaded/relocated?

**Comment by m-raab** [comment]
With Java 17 it is working, but I need the same function with Java 11.

**Comment by bmuschko** [comment]
In the last release, we upgraded Docker Java from 3.2.13 to 3.2.14. As a result, the transitive dependency for JNA changed from 5.8.0 to 5.12.1. Maybe that JNA versions became somewhat incompatible with Java 11.

**Comment by m-raab** [comment]
Will the problem be fixed?

**Comment by Sineaggi** [comment]
We just hit this issue internally.
```
Exception in thread "docker-java-stream-789163586" java.lang.UnsatisfiedLinkError: 'java.lang.String com.bmuschko.gradle.docker.shaded.com.sun.jna.Native.getNativeVersion()'
	at com.bmuschko.gradle.docker.shaded.com.sun.jna.Native.getNativeVersion(Native Method)
	at com.bmuschko.gradle.docker.shaded.com.sun.jna.Native.<clinit>(Native.java:223)
```
stacktrace shows exactly what's wrong, it tries to call `getNativeVersion` but the way jni maps java function names to c functions means it should be looking for `com_sun_jna_Native_getNativeVersion` and doesn't find that symbol.

**Comment by mattlong-finocomp** [comment]
This also affected me on Linux.

**Comment by bmuschko** [comment]
@mattlong-finocomp Can you provide a sample project or test case? So far I was not able to reproduce the issue.

**Comment by stefrev** [comment]
I know not useful, but also hitting this on upgrade to 9.1.0 - it only seems to affect when running on M1
```
Exception in thread "docker-java-stream-74049729" java.lang.UnsatisfiedLinkError: 'java.lang.String com.bmuschko.gradle.docker.shaded.com.sun.jna.Native.getNativeVersion()'
        at com.bmuschko.gradle.docker.shaded.com.sun.jna.Native.getNativeVersion(Native Method)
        at com.bmuschko.gradle.docker.shaded.com.sun.jna.Native.<clinit>(Native.java:223)
        at com.bmuschko.gradle.docker.shaded.com.github.dockerjava.transport.DomainSocket.<clinit>(DomainSocket.java:54)
        at com.bmuschko.gradle.docker.shaded.com.github.dockerjava.transport.UnixSocket.get(UnixSocket.java:29)
        at com.bmuschko.gradle.docker.shaded.com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl$2.createSocket(ApacheDockerHttpClientImpl.java:153)

```

**Comment by mattlong-finocomp** [comment]
@bmuschko I just added a commit to https://github.com/mattlong-finocomp/gradle-docker-plugin-error
I see the problem on Pop!OS 20.04 LTS (Ubuntu derivative).
I'm on AdoptOpenJDK 11.0.11+9.
I know this doesn't happen on Java 17.

Run `./gradlew buildImage` to see the problem.
I recommend running `./gradlew --stop` beforehand.
Switching the versions back to 9.0.1, running the gradlew stop command and then running buildImage results in a successful image build.
On 9.1.0 I've seen a few different failures modes: 
- the build spits out an UnsatisfiedLinkError and hangs indefinitely
- the build errors out with Could not initialize class com.bmuschko.gradle.docker.shaded.com.github.dockerjava.transport.DomainSocket
- the build errors out with java.lang.UnsatisfiedLinkError: 'java.lang.String com.bmuschko.gradle.docker.shaded.com.sun.jna.Native.getNativeVersion()'

**Comment by bmuschko** [comment]
So far I haven't been able to reproduce the issue on my Mac. I suspect https://github.com/bmuschko/gradle-docker-plugin/pull/1154 will fix it. Could one of you check out the branch, build the plugin locally, and try it out in your project to see if the issue has been fixed?

**Comment by AlexDumanskiy** [comment]
Same exception for a fresh installation of Ubuntu 22.04.1 with Java 11.0.17

**Comment by bmuschko** [comment]
@AlexDumanskiy I reverted the shading of Docker Java. Seems to have too many side effects. Can you try the branch again?

**Comment by AlexDumanskiy** [comment]
@bmuschko I would like to help, but I'm afraid I need some basic instructions on how do I use a plugin from a local jar in my project.

I cloned this repo and built in (had to skip functional tests due to fail of DockerListImagesFunctionalTest btw).
Built the jars, copied them to a directory named "libs" in my project.
Then added the following to build.gradle:

```
buildscript {
    repositories {
        flatDir { dirs 'libs' }
    }
    dependencies {
        classpath 'com.bmuschko:docker-spring-boot-application:9.1.1'
    }
}

plugins {
    id 'java'
    id 'application'
    id 'org.springframework.boot' version '2.6.6'
    // id 'com.bmuschko.docker-spring-boot-application' version '9.1.1'
}
```
There are no tasks from the plugin now.
If I uncomment the "id 'com.bmuschko.docker-spring-boot-application' version '9.1.1'" line I get 
```
* What went wrong:
Plugin [id: 'com.bmuschko.docker-spring-boot-application', version: '9.1.1'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.bmuschko.docker-spring-boot-application:com.bmuschko.docker-spring-boot-application.gradle.plugin:9.1.1')
  Searched in the following repositories:
    Gradle Central Plugin Repository
```

**Comment by big-andy-coates** [comment]
@AlexDumanskiy to locally build a version of one project and use it in another using Gradle you just need to install the built jars into your local maven repository.

So in this case:

1. clone this repo
2. run `./gradlew publishToMavenLocal`.  (This will build the jars and install them under `~/.m2/repository`)
3. note the version of the jars being build, probably something like `9.1.1-SNAPSHOT`
4. update your downstream project to consume this:
   a. add `mavenLocal()` to the main `repositories` section (not `buildscript` `repositories`)
   b. update the plugin version in the project to the version noted in step #3.

**Comment by AlexDumanskiy** [comment]
Task publishToMavenLocal not found:
```12:52:38 [0] gradle-docker-plugin >git status                                                                                                                                
On branch bm/exclude-jna
Your branch is up to date with 'origin/bm/exclude-jna'.
                                                                                                                               
12:52:45 [0] gradle-docker-plugin >./gradlew publishToMavenLocal                                                                                                             

> Configure project :
Inferred project: gradle-docker-plugin, version: 9.1.1-SNAPSHOT

FAILURE: Build failed with an exception.

* What went wrong:
Task 'publishToMavenLocal' not found in root project 'gradle-docker-plugin'.
```
trying to add a maven-publish plugin ...

**Comment by big-andy-coates** [comment]
Oh, that's annoying. Looks like the repo isn't set up for publishing locally.

https://docs.gradle.org/current/userguide/publishing_gradle_plugins.html#custom-plugin-repositories details how to do this, but following the steps locally (i.e. adding the ``maven-publish`` plugin) runs into another issue:

```
Execution failed for task ':publishPluginMavenPublicationToMavenLocal'.
> Failed to publish publication 'pluginMaven' to repository 'mavenLocal'
   > Artifact gradle-docker-plugin-0.0.1-SNAPSHOT.jar wasn't produced by this build.
```

**Comment by Sineaggi** [comment]
I believe that can be worked around by using
```kotlin
// for use with gradle publishToMavenLocal
publishing {
    publications {
        withType<MavenPublication>().configureEach {
            //artifact(tasks.shadowJar)
        }
    }
}
```

**Comment by bmuschko** [comment]
Did anyone have a chance to try out their build with my PR?

**Comment by bmuschko** [comment]
@AlexDumanskiy Can you please provide the error message you see in `DockerListImagesFunctionalTest`?

**Comment by big-andy-coates** [comment]
> Did anyone have a chance to try out their build with my PR?

I'll take a look tomorrow.

**Comment by big-andy-coates** [comment]
Or tonight...

I've tested this locally on my M1 Mac and images built perfectly 👍

**Comment by bmuschko** [comment]
Great, thanks. I am going to release a new version soon.
